In [1]:
import torch

tensor = torch.tensor([0,1,2, 3,4,5])
print(tensor.size())
unsqueeze_tensor = torch.unsqueeze(tensor, dim =1)
unsqueeze_tensor = torch.unsqueeze(unsqueeze_tensor, dim =2)
print (unsqueeze_tensor)
print (unsqueeze_tensor.size())

torch.Size([6])
tensor([[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]]])
torch.Size([6, 1, 1])


In [10]:
import sys
print(sys.executable)


/home/jun/miniconda3/envs/myblog/bin/python


In [3]:
import pandas as pd
from io import StringIO

# 주어진 CSV 데이터
csv_data = """
image_id,width,height,bbox,source
b6ab77fd7,1024,1024,"[834.0, 222.0, 56.0, 36.0]",usask_1
b6ab77fd7,1024,1024,"[226.0, 548.0, 130.0, 58.0]",usask_1
b6ab77fd7,1024,1024,"[377.0, 504.0, 74.0, 160.0]",usask_1
b6ab77fd7,1024,1024,"[834.0, 95.0, 109.0, 107.0]",usask_1
b6ab77fd7,1024,1024,"[26.0, 144.0, 124.0, 117.0]",usask_1
b6ab77fd7,1024,1024,"[569.0, 382.0, 119.0, 111.0]",usask_1
b6ab77fd7,1024,1024,"[52.0, 602.0, 82.0, 45.0]",usask_1
b6ab77fd7,1024,1024,"[627.0, 302.0, 122.0, 75.0]",usask_1
b6ab77fd7,1024,1024,"[412.0, 367.0, 68.0, 82.0]",usask_1
b6ab77fd7,1024,1024,"[953.0, 220.0, 56.0, 103.0]",usask_1
b6ab77fd7,1024,1024,"[30.0, 70.0, 126.0, 133.0]",usask_1
b6ab77fd7,1024,1024,"[35.0, 541.0, 46.0, 46.0]",usask_1
b6ab77fd7,1024,1024,"[103.0, 60.0, 117.0, 83.0]",usask_1
b6ab77fd7,1024,1024,"[417.0, 4.0, 110.0, 91.0]",usask_1
b6ab77fd7,1024,1024,"[764.0, 299.0, 119.0, 93.0]",usask_1
"""

# CSV 데이터를 DataFrame으로 읽어오기
df = pd.read_csv(StringIO(csv_data))

# 'image_id'로 그룹화
grouped = df.groupby(by='image_id')

# 그룹화된 데이터프레임을 딕셔너리로 변환
grouped_dict = {image_id: group for image_id, group in grouped}

# grouped_dict를 확인
for image_id, group in grouped_dict.items():
    print(f"image_id: {image_id}")
 
    print()

image_id: b6ab77fd7



In [2]:
print(group)

     image_id  width  height                          bbox   source
0   b6ab77fd7   1024    1024    [834.0, 222.0, 56.0, 36.0]  usask_1
1   b6ab77fd7   1024    1024   [226.0, 548.0, 130.0, 58.0]  usask_1
2   b6ab77fd7   1024    1024   [377.0, 504.0, 74.0, 160.0]  usask_1
3   b6ab77fd7   1024    1024   [834.0, 95.0, 109.0, 107.0]  usask_1
4   b6ab77fd7   1024    1024   [26.0, 144.0, 124.0, 117.0]  usask_1
5   b6ab77fd7   1024    1024  [569.0, 382.0, 119.0, 111.0]  usask_1
6   b6ab77fd7   1024    1024     [52.0, 602.0, 82.0, 45.0]  usask_1
7   b6ab77fd7   1024    1024   [627.0, 302.0, 122.0, 75.0]  usask_1
8   b6ab77fd7   1024    1024    [412.0, 367.0, 68.0, 82.0]  usask_1
9   b6ab77fd7   1024    1024   [953.0, 220.0, 56.0, 103.0]  usask_1
10  b6ab77fd7   1024    1024    [30.0, 70.0, 126.0, 133.0]  usask_1
11  b6ab77fd7   1024    1024     [35.0, 541.0, 46.0, 46.0]  usask_1
12  b6ab77fd7   1024    1024    [103.0, 60.0, 117.0, 83.0]  usask_1
13  b6ab77fd7   1024    1024     [417.0, 4.0, 11

In [4]:
from collections import defaultdict

res = defaultdict(list)

res['a'].append(1)
res['b'].append(2)
res['a'].append(3)

print(res)

defaultdict(<class 'list'>, {'a': [1, 3], 'b': [2]})


In [1]:
res1 = {}

res1['a'].append(1)
res1['b'].append(2)


print(res1)

KeyError: 'a'

In [2]:
import numpy as np

p = {
    'boxes': np.array([
        [100, 150, 200, 250],
        [120, 160, 220, 260],
        [140, 180, 240, 280]
    ])
}

first_column = p['boxes'][:, 0]
print(first_column)


[100 120 140]


In [4]:
import pandas as pd

df = pd.DataFrame({'value': [1,2,3], 'test': ['a', 'b', 'c']})

df.values.tolist()

[[1, 'a'], [2, 'b'], [3, 'c']]

In [8]:
import torch
import torch.nn as nn


m = nn.Linear(2, 5)
input = torch.randn(12, 2)
print(input)
output = m(input)
print(output.size())
print(output)


tensor([[-2.0494,  0.3071],
        [ 0.3813,  0.0309],
        [-0.5287,  0.9454],
        [ 0.8524, -0.9768],
        [-0.5810,  1.1458],
        [-0.3786,  0.4918],
        [ 1.6124, -2.9859],
        [ 2.0161,  0.7785],
        [-0.3739,  0.4907],
        [ 1.2721,  1.5783],
        [ 0.9634,  0.7011],
        [-0.2464, -0.5164]])
torch.Size([12, 5])
tensor([[-0.4017,  1.6131,  0.1700, -0.8103,  0.0834],
        [ 0.2459,  0.4188,  0.5133,  0.2581, -0.2550],
        [ 0.1840,  0.6595,  0.6197, -0.5834,  0.1144],
        [ 0.1590,  0.4301,  0.3034,  0.9845, -0.6062],
        [ 0.2133,  0.6357,  0.6687, -0.7122,  0.1799],
        [ 0.1268,  0.6968,  0.5145, -0.2798, -0.0371],
        [-0.0665,  0.5461, -0.1463,  2.3653, -1.2874],
        [ 0.8892, -0.6221,  1.0146,  0.4687, -0.2034],
        [ 0.1279,  0.6947,  0.5149, -0.2774, -0.0380],
        [ 0.8502, -0.4385,  1.1167, -0.2477,  0.1143],
        [ 0.5649, -0.0546,  0.8088,  0.1132, -0.1157],
        [-0.0591,  0.8846,  0.2454,  0

In [11]:
import torch
import torch.nn as nn

class TestModel(nn.Module):
    def __init__(self):
        super().__init__()  # nn.Module의 초기화 메서드를 호출합니다.
        self.layer1 = nn.Linear(10, 10)
        self.layer2 = nn.Linear(10, 10)

    def forward(self, x):
        out1 = self.layer1(x)
        out2 = self.layer2(out1.detach())
        return out2

model = TestModel()

In [21]:
x = torch.randn(1, 10)
a = model(x)
print('a: ',a)
print('a.mean(): ', a.mean())
a.mean().backward()
print(model.layer1.weight.grad)
print(model.layer2.weight.grad)

a:  tensor([[-0.4331, -0.9946, -0.7577,  0.5964, -0.4222,  0.4360, -0.2240,  0.2034,
          0.8203, -0.7823]], grad_fn=<AddmmBackward0>)
a.mean():  tensor(-0.1558, grad_fn=<MeanBackward0>)
None
tensor([[-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1896,  0.1069, -0.2750,  0.1658, -0.0010,
         -0.2374,  0.0260],
        [-0.2365,  0.0177,  0.0436,  0.1

In [24]:
import torch

w = torch.tensor(2.0, requires_grad = True)
y = w**3 + 10
y.backward()
w.grad

tensor(12.)